
package com.mycompany.proyectodb;

import javax.swing.JOptionPane;

/**
 *
 * @author ervargas
 */
public class frm_software extends javax.swing.JFrame {
    private String username; // Agrega una variable para almacenar el nombre de usuario

    /**
     * Creates new form frm_software
     */
    public frm_software(String username) {
        initComponents();
        this.username = username; // Almacena el nombre de usuario recibido
        loadUserInfo(); // Llama al método para cargar la información del usuario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_welcome_user = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_lastname = new javax.swing.JLabel();
        label_user_id = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        label_psswrd = new javax.swing.JLabel();
        Button_update_user_info = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_lastname = new javax.swing.JTextField();
        tf_user_id = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        tf_psswrd = new javax.swing.JTextField();
        Button_delete_acct = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(305, 410));
        getContentPane().setLayout(null);
        getContentPane().add(Label_welcome_user);
        Label_welcome_user.setBounds(20, 10, 250, 40);

        label_name.setText("Name:");
        getContentPane().add(label_name);
        label_name.setBounds(20, 110, 50, 30);

        label_lastname.setText("Lastname:");
        getContentPane().add(label_lastname);
        label_lastname.setBounds(20, 140, 70, 30);

        label_user_id.setText("User ID:");
        getContentPane().add(label_user_id);
        label_user_id.setBounds(20, 170, 70, 30);

        label_username.setText("UserName:");
        getContentPane().add(label_username);
        label_username.setBounds(20, 200, 80, 30);

        label_psswrd.setText("Password:");
        getContentPane().add(label_psswrd);
        label_psswrd.setBounds(20, 230, 70, 30);

        Button_update_user_info.setText("Actualizar informacion");
        Button_update_user_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_update_user_infoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_update_user_info);
        Button_update_user_info.setBounds(20, 280, 250, 30);

        jLabel1.setText("Informacion de usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 140, 30);

        tf_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        getContentPane().add(tf_name);
        tf_name.setBounds(110, 110, 160, 20);

        tf_lastname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_lastname);
        tf_lastname.setBounds(110, 140, 160, 20);

        tf_user_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        getContentPane().add(tf_user_id);
        tf_user_id.setBounds(110, 170, 160, 20);

        tf_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        getContentPane().add(tf_username);
        tf_username.setBounds(110, 200, 160, 20);

        tf_psswrd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_psswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        getContentPane().add(tf_psswrd);
        tf_psswrd.setBounds(110, 230, 160, 20);

        Button_delete_acct.setBackground(new java.awt.Color(255, 0, 51));
        Button_delete_acct.setText("Borrar cuenta");
        Button_delete_acct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_delete_acctActionPerformed(evt);
            }
        });
        getContentPane().add(Button_delete_acct);
        Button_delete_acct.setBounds(150, 330, 120, 24);

        btnexit.setText("Salir");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit);
        btnexit.setBounds(20, 330, 110, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // Cerrar el formulario actual (frm_software)
    this.dispose();
    
    // Abrir el formulario de inicio de sesión (frm_login)
    frm_login loginForm = new frm_login();
    loginForm.setVisible(true);
    }//GEN-LAST:event_btnexitActionPerformed

    private void loadUserInfo() {
        cls_admin_user adminUser = new cls_admin_user();
        adminUser.Read(username); // Llama al método Read con el nombre de usuario

        // Configura los campos de texto con la información recuperada
        tf_name.setText(adminUser.getName());
        tf_lastname.setText(adminUser.getLastname());
        tf_user_id.setText(adminUser.getUserId());
        tf_username.setText(adminUser.getUsername());
        tf_psswrd.setText(adminUser.getPassword());
        
        String fullName = tf_name.getText(); // Obtén el nombre desde el campo tf_name
        Label_welcome_user.setText("¡Bienvenido, " + fullName + "!");

    }

    private void tf_lastnameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tf_lastnameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tf_lastnameActionPerformed

    private void Button_delete_acctActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas borrar tu cuenta?",
                "Confirmar Borrado de Cuenta", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            cls_admin_user adminUser = new cls_admin_user();
            adminUser.delete(tf_user_id.getText());

            // Puedes añadir aquí cualquier lógica adicional después de eliminar la cuenta
            // Por ejemplo, cerrar la ventana actual, mostrar un mensaje, etc.

            JOptionPane.showMessageDialog(this, "Cuenta eliminada exitosamente.", "Cuenta Eliminada",
                    JOptionPane.INFORMATION_MESSAGE);

            // Cerrar la ventana actual después de eliminar la cuenta
            this.dispose();
        }
    }// GEN-LAST:event_Button_delete_acctActionPerformed

    private void Button_update_user_infoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Button_update_user_infoActionPerformed
        String newName = tf_name.getText();
        String newLastname = tf_lastname.getText();
        String newUserId = tf_user_id.getText();
        String newUsername = tf_username.getText();
        String newPassword = tf_psswrd.getText();

        // Llama al método Update de la clase cls_admin_user
        cls_admin_user adminUser = new cls_admin_user();
        adminUser.Update(newName, newLastname, newUserId, newUsername, newPassword);

        // Opcional: Vuelve a cargar la información actualizada
        loadUserInfo();
    }// GEN-LAST:event_Button_update_user_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_software.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_software.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_software.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_software.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_software().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_delete_acct;
    private javax.swing.JButton Button_update_user_info;
    private javax.swing.JLabel Label_welcome_user;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_lastname;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_psswrd;
    private javax.swing.JLabel label_user_id;
    private javax.swing.JLabel label_username;
    private javax.swing.JTextField tf_lastname;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_psswrd;
    private javax.swing.JTextField tf_user_id;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
