package com.mycompany.proyectodb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ervargas
 */
public class frm_create_user extends javax.swing.JFrame {

    /**
     * Creates new form cls_create_user
     */
    // Preparar consultas y traer consultas (se deben agregar librerias)

    public frm_create_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_name = new javax.swing.JLabel();
        label_lastname = new javax.swing.JLabel();
        label_user_id = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        label_psswrd = new javax.swing.JLabel();
        label_create_account = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_lastname = new javax.swing.JTextField();
        tf_user_id = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        tf_psswrd = new javax.swing.JTextField();
        button_create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(330, 375));
        setSize(new java.awt.Dimension(330, 330));
        getContentPane().setLayout(null);

        label_name.setText("Name:");
        getContentPane().add(label_name);
        label_name.setBounds(40, 60, 50, 30);

        label_lastname.setText("Lastname:");
        getContentPane().add(label_lastname);
        label_lastname.setBounds(40, 90, 70, 30);

        label_user_id.setText("User ID:");
        getContentPane().add(label_user_id);
        label_user_id.setBounds(40, 120, 70, 30);

        label_username.setText("User:");
        getContentPane().add(label_username);
        label_username.setBounds(40, 200, 80, 30);

        label_psswrd.setText("Password:");
        getContentPane().add(label_psswrd);
        label_psswrd.setBounds(40, 230, 70, 30);

        label_create_account.setText("CREATE YOUR ACCOUNT");
        getContentPane().add(label_create_account);
        label_create_account.setBounds(80, 10, 160, 40);

        tf_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tf_name);
        tf_name.setBounds(130, 60, 160, 20);

        tf_lastname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_lastname);
        tf_lastname.setBounds(130, 90, 160, 20);

        tf_user_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tf_user_id);
        tf_user_id.setBounds(130, 120, 160, 20);

        tf_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tf_username);
        tf_username.setBounds(130, 200, 160, 20);

        tf_psswrd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tf_psswrd);
        tf_psswrd.setBounds(130, 230, 160, 20);

        button_create.setText("Create");
        button_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_createActionPerformed(evt);
            }
        });
        getContentPane().add(button_create);
        button_create.setBounds(110, 280, 100, 30);

        jLabel1.setText("-----------Login Credentials-----------");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 170, 220, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lastnameActionPerformed

    private void button_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_createActionPerformed

        cls_admin_user registrar = new cls_admin_user();
        registrar.Create(tf_name.getText(), tf_lastname.getText(), tf_user_id.getText(), tf_username.getText(), tf_psswrd.getText());

        frm_login login = new frm_login();
        login.setSize(330, 330);
        login.setVisible(true);

        // Esconde la ventana de creacion de usuario.
        this.hide();

    }//GEN-LAST:event_button_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_create_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_create_account;
    private javax.swing.JLabel label_lastname;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_psswrd;
    private javax.swing.JLabel label_user_id;
    private javax.swing.JLabel label_username;
    private javax.swing.JTextField tf_lastname;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_psswrd;
    private javax.swing.JTextField tf_user_id;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
